name: Aurelien Guitton - Game Designer Portfolio
email: aurelien.guitton@hotmail.com
description: Student in Video Games master's degree at Université du Québec à Chicoutimi. Check out the games I made and get in touch!
url: https://aureliengttn.github.io/
social:
  name: Aurelien Guitton
  links:
    - https://twitter.com/AurelienGttn
    - https://facebook.com/aurelien.guitton
    - https://github.com/AurelienGttn/
    - https://aureliengttn.itch.io
    - https://www.linkedin.com/in/aurelien-guitton/


plugins:
  - jekyll-seo-tag

collections:
  portfolio:

google_analytics: UA-24856910-2